name: Continuous Integration
on:
  push:
    branches:
      - 'master'
  pull_request:
jobs:
  get-previous-tag:
    name: Test Get Previous Tag on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags
      - name: 'Get Previous tag'
        id: previoustag
        uses: ./
      - run: |
          pwd
          ls -la
          ls -l .git/refs/tags/*
          git for-each-ref --sort=-taggerdate --count 1 --format="%(refname:short)" "refs/tags/*"
          echo "Tag: ${{ steps.previoustag.outputs.tag }}"
          echo "Timestamp: ${{ steps.previoustag.outputs.timestamp }}"
          test -n "${{ steps.previoustag.outputs.tag }}"
          test -n "${{ steps.previoustag.outputs.timestamp }}"
      - name: Remove tags
        uses: JesseTG/rm@v1.0.2
        with:
          path: .git/refs/tags
      - name: 'Get Previous tag with fallback'
        id: previoustagwithfallback
        uses: ./
        with:
          fallback: v1.0.0
      - run: |
          echo "Tag: ${{ steps.previoustagwithfallback.outputs.tag }}"
          echo "Timestamp: ${{ steps.previoustagwithfallback.outputs.timestamp }}"
          test -n "${{ steps.previoustagwithfallback.outputs.tag }}"
          test -n "${{ steps.previoustagwithfallback.outputs.timestamp }}"
